### ISSUE TITLE
extra alpha mask

### ISSUE THREAD

**Issue by z0yuu** [takiyu/portrait_matting#1]
May I ask How to get the extra alpha mask ?

**Comment by highland0971** [comment]
The same question with @z0yuu , where can we download the extra alpha mask to reproduce the model ? Thanks.

**Comment by GuideWsp** [comment]
We have make alpha by ourselves, but we can't get similar result. If possible, please give some advise.

**Comment by zhujun001** [comment]
you could run  scripts/prepare_matting_dataset.py before scripts/prepare_seg_tri_dataset.py. prepare_matting_dataset.py will generate a pesudo alpha mask by gaussian blur

**Comment by leaf918** [comment]
> you could run scripts/prepare_matting_dataset.py before scripts/prepare_seg_tri_dataset.py. prepare_matting_dataset.py will generate a pesudo alpha mask by gaussian blur

Wonderful!!

**Comment by mansentan** [comment]
> you could run scripts/prepare_matting_dataset.py before scripts/prepare_seg_tri_dataset.py. prepare_matting_dataset.py will generate a pesudo alpha mask by gaussian blur

@zhujun001, I'm getting following error when I run scripts/prepare_matting_dataset.py, do you have idea to it? 

`[2019/03/24 11:07:11.723] INFO (1666) __main__	: Compute look up table for weights
Traceback (most recent call last):
  File "scripts/prepare_matting_dataset.py", line 146, in <module>
    main()
  File "scripts/prepare_matting_dataset.py", line 135, in main
    weight_lut = AlphaWeightLut(names, config.img_alpha_dir)
  File "scripts/prepare_matting_dataset.py", line 72, in __init__
    self.distrib_lut = -np.log(sum_distrib / np.sum(sum_distrib))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'NoneType'`

**Comment by wkunique** [comment]
try
python scripts/prepare_matting_dataset.py --pseudo_alpha

**Comment by mansentan** [comment]
thanks @wkunique, you are saving my life.

**Comment by Maru-chan511** [comment]
@zhujun001 Thanks for a million!

**Comment by nicho2605** [comment]
> 
> 
> try
> python scripts/prepare_matting_dataset.py --pseudo_alpha

i still having nonetype error after using --psuedo_alpha
anyone can help ?

currently using numpy 1.13.3
