### ISSUE TITLE
Error running Generate mean masks and grids.

### ISSUE THREAD

**Issue by usalexsantos** [takiyu/portrait_matting#19]
When running the Generate mean masks and grids, I'm getting this error message.

lotlib.fontconfig_pattern', 'pyparsing', 'matplotlib.colors', 'matplotlib._color_data', 'cycler', 'matplotlib._version', 'dateutil', 'dateutil._version']
Traceback (most recent call last):
  File "scripts/prepare_seg_plus_dataset.py", line 21, in <module>
    from face_mask import FaceMasker
  File "D:\Portrait_Matting\scripts\face_mask.py", line 10, in <module>
    from .face_detector import FaceDetector
ImportError: attempted relative import with no known parent package

Can you help me?

**Comment by mansentan** [comment]
Change "from .face_detector import FaceDetector" to "from face_detector import FaceDetector" will solve the problem.
