### ISSUE TITLE
test error ,who can help me?

### ISSUE THREAD

**Issue by billzw** [takiyu/portrait_matting#24]
(venv) [c@localhost portrait_matting]$ ./scripts/test.py --mode seg --model_path=result/model_best -i t2.jpg 
[2019/05/16 09:05:17.683] INFO (20005) config   : Load config from "config.json"
[2019/05/16 09:05:17.683] INFO (20005) models   : Create FCN8s for segmentation
[2019/05/16 09:05:19.513] INFO (20005) transforms       : Create transform function of segmentation
[2019/05/16 09:05:19.514] INFO (20005) __main__ : Load input file: t2.jpg
Traceback (most recent call last):
  File "./scripts/test.py", line 162, in <module>
    main(sys.argv[1:])
  File "./scripts/test.py", line 137, in main
    ret = predictor.predict(img)
  File "./scripts/test.py", line 78, in predict
    inp = self._transform(inp)[0]  # Use only inputs (no teacher)
  File "/home/c/PycharmProjects/portrait_matting/scripts/transforms/dataset_transform.py", line 23, in transform_seg
    assert len(inputs) == 2
AssertionError

**Comment by ghost** [comment]
@billzw did you solve this issue? Can you provide your solution? Thanks!
